name: 'github-commit-lint'
description: 'Checks commit message for proper format'
branding:
  icon: 'tag'
  color: 'gray-dark'
inputs:
  version:
    description: 'version# to set'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
